foodsearch/foodsearch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls), 
    path('', include("foodweb.urls"))
]

foodsearch/foodweb/urls.py
from django.urls import path
from . import views 

app_name = "Foodweb"
urlpatterns = [
    path('', views.search, name="Search"), 
    path('allresturants', views.resturant, name="allResturant"),  
    path('<str:menu_id>/menu', views.resturantmenu, name="Menu"),   
]

foodsearch/foodweb/models.py
from django.db import models 

# Create your models here.

class resturants(models.Model): 
    hotel_id = models.BigIntegerField()
    hotel_name = models.CharField(max_length= 200)  
    # hotels_name = models.CharField(max_length= 200) 
    hotel_location = models.CharField(max_length=200)
    hotel_langitude = models.CharField(max_length=200)
    hotel_longitude = models.CharField(max_length=200) 
    
    def __str__(self) -> str:
        return str(self.hotel_id)

class menus(models.Model):
    hotel_id = models.ForeignKey(resturants, on_delete=models.CASCADE)
    food = models.CharField(max_length=200)
    price = models.CharField(max_length=100)
    
    def __str__(self):
        return self.food
    
# to scrape data points form given csv file 
# from .scrap import Command    
# obj = Command()
# obj.handle()    

foodsearch/foodweb/views.py
from django.shortcuts import render, get_object_or_404
from .models import menus, resturants

# Create your views here.
def resturantmenu(request, menu_id): 
    menu = get_object_or_404(resturants, hotel_id=menu_id) #
    context = {
        "menu": menu, 
    }
    return render(request, 'foodweb/mainpage.html', context) 

def search(request):
    query = request.GET.get('query') 
    dishes = menus.objects.filter(food=query) if query else []
    context= {
        'query': query,
        'dishes': dishes,
    }
    return render(request, 'foodweb/search.html', context) 


def resturant(request):
    res = resturants.objects.all()
    context = {
        'res' : res,
    } 
    return render(request, "foodweb/resturant.html", context) 

foodsearch/foodweb/templates/foodweb/mainpage.html
<!DOCTYPE html>
<html>
<head>
    <title>Menu</title>
</head>
<body>
  <fieldset>
    <legend><h1>{{ menu.hotel_name }}</h1></legend>  
    <ul>
        <li> HOTEL LOCATION: {{ menu.hotel_location}} </li> 
        <li> GEOGRAPHIC LOCATION: ({{ menu.hotel_langitude}},{{ menu.hotel_longitude}}) </li> 
    </ul>
    <hr>
    <h1 style="margin-left: 200px; "> MENU </h1>
    <div style="text-align: center;">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <table >
        <tr>
          <th>DISH</th>
          <th>PRIZE</th>
        </tr>
    {% for choice in menu.menus_set.all %}
    <tr>
        <td>{{ choice.food }}</td>
        <td>{{ choice.price }}</td> 
    </tr>
    {% endfor %} 
</table 
</div>
</fieldset>
</html>

foodsearch/foodweb/templates/foodweb/resturant.html
<!DOCTYPE html>
<html>
<head>
    <title>Dish Search</title>
</head>
<body> 
    <fieldset>
        <legend><h1>Available  Restaurants </h1></legend>
    {% if res %}
        <ul>
            {% for i in res %}
                <li><a href="{% url 'Foodweb:Menu' i.hotel_id%}">{{ i.hotel_name }} </a> </li>

            {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p>
    {% endif %} 
    </fieldset>
</body>
</html>

foodsearch/foodweb/templates/foodweb/search.html
<!DOCTYPE html>
<html>
    <style>  
        body {
            font-family: Arial;
          }
          
          * {
            box-sizing: border-box;
          }
          
          form.example input[type=text] {
            padding: 10px;
            font-size: 17px;
            border: 1px solid grey;
            float: left;
            width: 80%;
            background: #f1f1f1;
          }
          
          form.example button {
            float: left;
            width: 20%;
            padding: 10px;
            background: #2196F3;
            color: white;
            font-size: 17px;
            border: 1px solid grey;
            border-left: none;
            cursor: pointer;
          }
          
          form.example button:hover {
            background: #0b7dda;
          }
          
          form.example::after {
            content: "";
            clear: both;
            display: table;
          }
        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 4px;
        } 
        .button:hover {
            background: #0b7dda;
          }
          
    </style>
<head>
    <title>Dish Search</title>
</head>
<body> 
    <fieldset>
        <legend><h1> Search Your Favorite Dish </h1> </legend>
    <form method="GET" class="example">
        <input type="text" name="query" value="{{ query }}" placeholder="Search for a dish">
        <button type="submit">SEARCH</button>
    </form>
    <hr>
    {% if dishes %}
        <h2>Search Results:</h2>
        <table >
            <tr>
              <th>DISH</th>
              <th>PRIZE</th>
            </tr>
            {% for dish in dishes %} 

            <tr>
                <td>{{ dish.food }}</td> <td> {{dish.price}}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No results found.</p>
    {% endif %} 

    <a href= "{% url 'Foodweb:allResturant' %} " class="button"> ALL REGISTERD RESTAURANTS </a> 
    </fieldset>
</body>
</html>